# Docker
# Build a Docker image

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: aquasecScanner@4
      inputs:
        image: 'mongo-scan'
        scanType: 'hosted'
        register: false
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '4.2.0'
        registry: 'Docker Hub'
        windowsScannerVersion: '4.2.0'