# Docker

# Build a Docker image

trigger: none
pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Aqua
      inputs:
        command: login
        containerRegistry: aqua-register    
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: java-demo
        tags: |
          latest
    - task: aquasecScanner@4
      inputs:
        image: 'java-demo'
        scanType: 'local'
        register: false
        hideBase: false
        showNegligible: true
        connection: 'demo2404'
        scanner: 'registry.aquasec.com/scanner:6.2.preview6'
        scanMalware: true
        showWillNotFix: true
