# Docker

# Build a Docker image

trigger: none
pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Aqua
      inputs:
        command: login
        containerRegistry: aqua-register    

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: build
        repository: alpine
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          3
    - task: aquasecScanner@4
      inputs:
        image: 'alpine:3'
        scanType: 'local'
        registry: 'Docker Hub'
        hideBase: false
        showNegligible: true
        connection: 'demo2404'
        scanner: 'registry.aquasec.com/scanner:6.0'
